### ISSUE TITLE
Use ldbc_graphalytics_platforms_reference as reference implementation

### ISSUE THREAD

**Issue by mihaic** [ldbc/ldbc_graphalytics_docs#1]
I thought the reference implementation is https://github.com/ldbc/ldbc_graphalytics_platforms_reference. However, the specification says it is OpenG:
https://github.com/ldbc/ldbc_graphalytics_docs/blob/master/tex/definition.tex#L313

For ease of understanding the code, I prefer ldbc_graphalytics_platforms_reference.

**Comment by wlngai** [comment]
Thank you for the feedback! The reference implementation remains as https://github.com/ldbc/ldbc_graphalytics_platforms_reference, which provides a simple but correct implementation of all supported algorithms. However, OpenG is used to generate validation outputs (if possible) for all graphs, which cannot be done by the reference implementation in any reasonable amount of time.

This distinction is not clear in section 2.4 of the technical specification, which will be clarified in the next release.

**Comment by mihaic** [comment]
How is OpenG output validated?

**Comment by szarnyasg** [comment]
This is an old issue, but let's discuss this for completeness:

> I thought the reference implementation is https://github.com/ldbc/ldbc_graphalytics_platforms_reference. However, the specification says it is OpenG: [...]
This was resolved as the `ldbc_graphalytics_platforms_reference` repository is now linked as the reference implementation:
![image](https://user-images.githubusercontent.com/1402801/60356274-dd815a00-99d0-11e9-8ee6-1f9e5a01f077.png)

> How is OpenG output validated?
Results are cross-validated between implementations, first between Giraph, Graphmat, and OpenG, then for other implementations such as GraphX.
