### ISSUE TITLE
Undefined minimum integer size for edge weights

### ISSUE THREAD

**Issue by mihaic** [ldbc/ldbc_graphalytics_docs#3]
https://github.com/ldbc/ldbc_graphalytics_docs/blob/master/tex/definition.tex#L30
We should specify at least 32-bit support.

**Comment by szarnyasg** [comment]
This is a rather old issue, but let's see if we can resolve or close it. The said line and the preceding paragraph states:

> Each vertex is assigned a unique identifier represented as a signed 64-bit integer, i.e., between $-2^{63}$ and $2^{63}-1$. Vertex identifiers do not necessarily start at zero, nor are the identifiers necessarily consecutive. Edges are represented as pairs of vertex identifiers. Graphalytics supports both \emph{directed} graphs (i.e., edges are unidirectional) and \emph{undirected} graphs (i.e., edges are bidirectional). Every edge is unique and connects two distinct vertices. This implies that self-loops (i.e., vertices having edges to themselves) and multi-edges (i.e., multiple edges between a pair of vertices) are not allowed. In the case of undirected graphs, for every pair of vertices $u$ and $v$, the edges $(u,v)$ and $(v,u)$ are considered to be identical.
>
> Vertices and edges can have properties which can be used to store meta-data such as weights, timestamps, labels, costs, or durations. Currently, Graphalytics supports three types of properties: \emph{integers}, \emph{floating-point numbers}, and \emph{booleans}. **All floating-point numbers must be internally stored and handled in 64-bit double precision IEEE-754 format. We explicitly do not allow the single precision format,** as this can speedup computation and presents an unfair advantage. Integers can be stored and processed in any format which seems suitable by the system.

Where should we include 32-bit support in Graphalytics 2.0?

**Comment by szarnyasg** [comment]
Following a discussion with @thegeman and @amusaafir , we noted that the current version of Graphalytics does not use boolean/integer properties.
