### ISSUE TITLE
Local Clustering Coefficient formula is wrong

### ISSUE THREAD

**Issue by hegyibalint** [ldbc/ldbc_graphalytics_docs#7]
In Section 2.3.5, formula 2.7 is not correct. 

In the numerator of the formula, (N(v) U N_in(u)) is counted over all the neighbors of vertex v. Because the complete N(v) is part of the resulting set, too many edges will be counted.
I assume instead of an union, the writer wanted to use intersection.

**Comment by AhmedMusaafir** [comment]
Thanks for pointing this out - https://github.com/ldbc/ldbc_graphalytics_docs/commit/7cd832a7207d81edee27ebd0ec395a4b1b75f5f3
